site_name: CoolLIFE Wiki
site_url: https://github.com/coollife-project/wiki/
repo_url: https://github.com/coollife-project/wiki/wiki
edit_uri_template: '{path_noext}/_edit'  # https://www.mkdocs.org/user-guide/configuration/#edit_uri_template
hooks:
  - change_edit_url.py
  - add_id_to_first_h1.py
extra_css:
  - custom.css
markdown_extensions:
  - pymdownx.magiclink  # Convert bare URLs into hyperlinks
  - attr_list  # Allow setting attributes on block elements
plugins:
  - search
extra:
  generator: false  # Hide "Made with Material for MkDocs"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coollife-project/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/CoolLIFE_EU
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/coollife_project/
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: https://raw.githubusercontent.com/coollife-project/.github/main/logo.png
  logo: https://raw.githubusercontent.com/coollife-project/.github/main/logo.png
  icon:
    repo: fontawesome/brands/github
    # edit: material/file-edit-outline
  features:
    - content.action.edit  # Show Edit Page
    - navigation.top  # Show "Back to Top" on scrolling
    # - navigation.expand  # Expand left menu sections
    - navigation.footer  # Show footer navigation
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
extra_javascript:
  - assets/translation.js
  - assets/uploads/coollife_training.pptx
  - assets/uploads/dhc_final.pptx
  - assets/uploads/dsc_training.pptx
  - assets/uploads/ehp_webinar.pptx

# nav:
#   - For Authors:
#     - Create New Page: https://github.com/coollife-project/wiki/wiki/_new

nav:
  - "Getting Started":
    - welcome-page-introduction-to-the-coollife-project.md
  - "CoolLIFE Tool Overview and User Guide":
    - key-capabilities.md
    - user-interface-navigation.md
    - core-functions.md
    - general-workflow.md
    - data-upload.md
    - data-export.md
  - "Calculation Modules of the CoolLIFE Tool":
    - "Cooling":
      - cm-space-cooling-demand.md
      - cm-technologies-and-measures.md
      - cm-comfort-lifestyle-and-user-behaviour.md
      - cm-economic-feasibility.md
      - cm-demand-side-management-demand-response.md
    - "District Cooling":
      - cm-district-cooling.md
    - "Policy":
      - legal-and-regulatory-aspects.md
    - "Finance":
      - financial-instruments.md
  - "How to Apply the CoolLIFE Tool":
    - use-case-1-sc-integration-in-the-energy-efficiency-sector.md
    - use-case-2-strategic-planning-of-space-cooling.md
    - use-case-3-space-cooling-at-the-building-level.md
    - use-case-4-data-for-sc-planners.md
    - use-case-5-reduction-of-energy-consumption-due-to-sc-in-buildings.md
    - use-case-6-sc-integration-in-energy-communities.md
    - use-case-7-comprehensive-assessment-report.md
  - "Learning Center":
    - learning-center.md
    - beyond-the-tool-and-the-hub.md
    
  
  
